[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec3 = { path = "vec3" }
image = "0.23.1"
rand = "0.8.4"
crossbeam = "0.8.1"